version: "3.5"

services:
  nginx:
    env_file:
      - .env
    container_name: nginx_container
    image: nginx
    working_dir: /www
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      - php
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./:/www:delegated
    networks:
      - app

  php:
    env_file:
      - .env
    container_name: php_container
    image: dumitrupascal/laravel_psql:latest
    working_dir: /www
    depends_on:
      - postgres
    volumes:
      - ./:/www:delegated
    networks:
      - database
      - app

  postgres:
    env_file:
      - .env
    container_name: ${DB_HOST:-postgres_container}
    image: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE:-test_db}
      POSTGRES_USER: ${DB_USERNAME:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      PGDATA: /data/postgres
    volumes:
      - ./postgres_db:/data/postgres
    ports:
      - "${DB_PORT:-5050}:5432"
    networks:
      - database
    restart: unless-stopped

  pgadmin:
    env_file:
      - .env
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-1234}
    depends_on:
      - postgres
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - database
    restart: unless-stopped

networks:
  app:
    driver: bridge
  database:
    driver: bridge

volumes:
  nginx:
  php:
  postgres:
  pgadmin:
